INITIAL_DISCOUNT = { :days => 3, :discount => 0.1 }
MEDIUM_DISCOUNT = { :days => 10, :discount => 0.3 }
ADVANCE_DISCOUNT = { :days => 10, :discount => 0.5 }
COMMISSION_RATE = 0.3
INSURANCE_RATE = 0.5
ASSISTANCE_FEE = 100 # per_day

### OPTIONS (IN CENTS)###
GPS_FEE = 500
BABY_SEAT_FEE = 200
ADDITIONAL_INSURANCE_FEE = 1000
